language: scala

scala:
  - 2.12.4

sudo: false
script: $TRAVIS_BUILD_DIR/travis/script/build.sh

jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2
  - $HOME/.ivy2
  - $HOME/.sbt

git:
  submodules: false
  
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

env:
  global:
  - secure: dt9QjDCwqwq4/uh96xwld7yimg6Is0P+td2/WweJvH4VlU8EvaILq217Hqd5LSjTUWcwp2TINbmngVDb1VDmqiTBWT7PqMo0VV+4IaK05ar+6cr+MLRWUb3KlfC35/1z+ZU2lASCztLZ6R9UqukIk4ZlxmAzoOfG7VxN3YKUDAg4yMv9ZrNI2ZWNhuGPgtzKoyFDhV9UZSiQVeN23XsI+af0uH+vkgKlDEh5rDRPrWIyTYgVtUJG5MnMJZ5je/sVmgu0o0LGc+VCSFd6T8r/mPIDI3l27eKSboGshoiwklk/h2mvgtNOc9oM8HE+T29EsHQcUtQ2MNYQ1EW/lCy4bwZP//ipLafoPh1cMKpH6eCidn0qC3a9mU0KGL2rW+ytC2XgADRcO81qnDTojNMJCVbRJMuyb3MjBVZOuEKVl0Q47OxiQ1lNds0GzfDcILvy2NFRNZlZCw+vapxY1Ril62ep9/QRkMtIn7JQrxiXksIH+3zGOO01IyUEpxN2CglHYYX4Up5yKB2mo/g27HdAzSwqtIeIBiNOcLKy0288TWRto6yHoe8v1Bu4JGkDHOfRGd7UmxDkl7J2ckN+xYyL+wwwp6N1MAfzmZmyHgQlZsAewmiIbxPXukfbg49Ybrk0XpREFYkqHZYPIntQ1cDtb7DufN7ShI//+JqL4ScnKPY=
  - secure: PJ6yxJ/hy9o+nUfe0bkaQhokc8OoSKFo1TBb2PQsMoELvSzwBCWc78DSzzZqocg0x9dFG5rGhOFidR5t8P1vWL/qvGJHbNpzVBajZMKdjDlQrtNVcieWLxXRUKhdJ+yS0Vu8LVtznLsZvRrmeNcz1k9i2dyF2uMchXznHiLzmlt5mhPVsvHthLxJZtYUQeZHk7cJ9J4BnO0o+ANmVdKUxDPmsEdYPZoiV1z3+BefBVCTNOth1fWIVM4S0MTI5ZL7B3hrHNf96UNykhJ9Nz8jlyJiFPD4PxfNoRCVbGkh1c3JTsf7lYqQB3imLEUCv2tlO3Gd+ySdP5PiH9m9SLwJND3MVAQaqoZrY+90cuc9noB0YhZZ4eFyICaUuODUc1TeFVnm4kye3MpgKg2NXr6mWd6AO5oczZdw8xkzDJdrb5P2XUkjf4VSCaeC7ZBUa5f2+id612nVuvBsf5yNXheWgP5z5qttYJXlcGgSnSnPfwiWcg+/4tGxilZHyeb6Hgp9q9GKEE3YrIHHH12+ZEtJHMAD60mcCvGpzEs6J0Zgf3F3XF49KgtRYJvO3Gb/Z7LBIAJQS2xeqIuZcpNqFMfgW3vRI+HjZ5T5QzJ0/MvPV3Z3hCIkPfvailga/Fc4wSTLZ2f9EoIEQ1FItP71izFeZ8J7bJHknIWUIf7Lh5aBzDk=
  - secure: S1Dxk6d/mgqv8ZHzNh2rxFYaZ0H9l6KkvRCRNivUewk9QfeHOHMe9E/GSXBYrWlCflVTaCTJ/iOUDHBeJ4rbd5YWNvdwWnZLFXkx3vKKUC3ZEMjh8MR/78oD6U6yhN2odye52lL3X2VLH4QoYcMp7I5La8MX6+KEbaVexOkMcSUfd0PBFIaErMnnpzqmELjGKW6ahmbilCwg431Kz6iG3DhdeC1cH4YFlJlUCer9qJusebjC7u/6OjKX3RAWVMD4NCEyrdc83iM5jTakVklFVtdA2I6qM7qS5ME0pECLzCKPybzrx3tZuAcpyUzFunetEfSMdt5PheiaCGKT3oPsCaf16QNgQ3qRvG3T8u+lKTNMEUe5lBkfM2e5kHG3RJ0FfTjhgGVmHNf1GirnygprGWIxUQ6vstLctlADRGhToqZi1qKTDc8RUN8jzr9rFVF3/MkDXAeglFxlBbIfOjim3FrBSyX2uKAGNqRIpbF6sDvWaJSUwu68SseHLEqbm4C9+ZNnRNAi2e+vBTeqXlo+P2wTHhoHU6AnItsnYNGspow5n5RTXptf4jjqnBhNXHXc6x0seLQ+ekeGmqH68Pu75iVSoD0DNKfjtkkUKAtoUD12fWoZl6YuPSsWY4OvBXRCNhUq2gpoNoyHhTW9Q5HMp4OtQ8W4Swtko4UmJ9TK0hg=
  - secure: em0b4m9jogJq0Ve2VZfY+vdlBACZMPNBhkjfKsDpGlpPmNJGTHqEGKWDB8jFw5Akd39bNR4CmqGYI9EEG/a7Vkm6xz/o05PAZHVIk04hcTBU11HTTT+C+8+woYKStdnzdpn3wWdDV+LysOQqjjC4wb7VuPEYrsb+IKaA+dhZVcmwC7YKu/YQDs26e2sQkOQB6BnYx2bvYWm6HphxpQa+0rTqvdLPmQ70OXce9nkSruLeha1aHDZgPR5mYrzqg93nbvhT1o8VEoPRuMCoMuwYy4JdaIMzsKkZJl3KZdjtuEQ5dKbNlIyf3Fa68Dx/mvgwykcm/iyGMDnkm7JQU2efvq5cZhWvHOKyQpkDqSG0pTx5Q8k4pgppYjJgQ847IyV0FiLuYoGZjym9SQj21TBR+fu6f2caD6YkC7FgBW/Cqvv802+BfQ1gpYkWHwyXk4BLUmlVNDy1Kp6+HvmUg4Ngw2gNWGt9/h+6XMS9fBfFGJOqjEFvnYSWokMJsK/8a+3k+ACXNd5gx2CFsjjQWdgbsqCZWUj94wrhgcdOzlnHXU7WWbB7n5HXoPXveBASknTfDPAmpJ/yc4M5lK1o3AO5X1je/l4zlFzgLwM5HsjUJT9pz/X2CbL4ljBYTaaYFfw1cWPFpQdGBdpngHMuwWKixKmnf4IZ/2MPr4zX8Wk6C80=
