#%RAML 1.0
title: Test API
baseUri: hb://test
types:
  BookTag:
    enum: [new,best-seller,classics]

  BookProperties:
    type: object
    properties:
      publish_year:
        type: number
        format: int16
      sold: integer
      issn: string
      tag: BookTag

  Book:
    type: object
    properties:
      book_id: string
      author_id: string
      book_name: string
      author_name: string
      book_properties: BookProperties

  BookTransaction:
    type: object
    properties:
      transaction_id: string

  BookCreatedTransaction:
    type: object
    properties:
      transaction_id: string

  Click:
    type: object
    properties:
      click_url: string
      extra: object

  ClickConfirmation:
    type: object
    properties:
      id: string
      extra?: object

  ClicksInformation:
    type: object
    properties:
      count:
        type: number
        format: long
      last_registered:
        type: datetime
        required: false
      first_inserted?: datetime

  Author:
    type: object
    properties:
      name: string
      books:
        type: Book[]

/authors/{author_id}/books/{book_id}:
  uriParameters:
    author_id: string
    book_id: string
  get:
    responses:
      200:
        body:
          application/json:
            type: Book
  put:
    body:
      application/json:
        type: Book
    responses:
      200:
        body:
          application/json:
            type: object
      201:

  feed:put:
    body:
      application/json:
        type: Book

/authors/{author_id}/books:
  uriParameters:
    author_id: string
  get:
    responses:
      200:
  post:
    body:
      application/json:
    responses:
      200:
        body:
          application/json:
            type: BookTransaction
      201:
        body:
          application/json:
            type: BookCreatedTransaction

/clicks:
  post:
    body:
      application/json:
        type: Click
    responses:
      201:
        body:
          application/json:
            type: ClickConfirmation
  get:
    responses:
      200:
        body:
          application/json:
            type: Click[]
/clicks/{click_url}:
  uriParameters:
    click_url: string
  get:
    queryParameters:
      sort_by: string
      filter:
        type: string
        required: false
    body:
      application/json:
        type: ClicksInformation
